app_name: framework-python
log_level: DEBUG
basepath: /home/ya/mapdata/
baseurl: 146.56.208.127
baseport: 33069
projid: mb
picmoudle:
rabbitmq:
  sourceip: 146.56.208.127
  amqpport: 5672
  myvhost: /
  queue: framework-python